### ISSUE TITLE
Won't autoScroll or mouseScroll to the right

### ISSUE THREAD

**Issue by smcgovern** [tkahn/Smooth-Div-Scroll#37]
I am trying to have my gallery autoscroll to the right as well as have it be able to mousescroll but it only seems to work in one direction.  I'm sure its my implementation of it but I cannot get to the bottom of it.

http://modworldwide.com/10rsq/gallery_test/

**Comment by oompt** [comment]
I suffered with the same bug. I found that any time the right hover-able element extended beyond the width of the viewport, the script would break. 

Here is an illustration. The top line is the viewport width (which is the same as the parent div). Notice that when there is enough space on the right side of the hover-able element, things work fine. If it extends *beyond* the parent's width, it seems to break. 

![Illustration](http://f.cl.ly/items/04213v1m3E0D2B0M3a1M/Image%202015-06-24%20at%204.49.58%20PM.png)

If you just play with the width of that div, and then centre it, it should work fine. 

`
#makeMeScrollable { 
    width: 99%;
    margin: 0 auto;
}
`

**Comment by oompt** [comment]
Additionally, the above would seem to indicate that the issue is not so much with the right side, or right scrolling. Rather, the issue is with margins. I think if the #makeMeScrollable div was aligned to the right hand side, the *leftward* scrolling would likely break.
